### ISSUE TITLE
一直失败不知道哪里错了，麻烦看一下，谢谢

### ISSUE THREAD

**Issue by daweiwood** [Squaregentleman/mimotion#47]
Run pip install requests
Collecting requests
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting chardet<5,>=3.***.2
  Downloading chardet-4.***.***-py2.py3-none-any.whl (178 kB)
Collecting certifi>=2***17.4.17
  Downloading certifi-2***2***.12.5-py2.py3-none-any.whl (147 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.1***-py2.py3-none-any.whl (58 kB)
Installing collected packages: urllib3, idna, chardet, certifi, requests
Successfully installed certifi-2***2***.12.5 chardet-4.***.*** idna-2.1*** requests-2.25.1 urllib3-1.26.4
Traceback (most recent call last):
  File "main.py", line 221, in <module>
    push += main(user_list[line], passwd_list[line], step) + '\n'
  File "main.py", line 73, in main
    login_token,userid = login(user,password)
  File "main.py", line 31, in login
    location = r1.headers["Location"]
  File "/opt/hostedtoolcache/Python/3.7.1***/x64/lib/python3.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
Error: Process completed with exit code 1.

**Comment by Squaregentleman** [comment]
登陆出错 你账号密码对了吗
