### ISSUE TITLE
不知道哪里问题

### ISSUE THREAD

**Issue by zyx901212** [Squaregentleman/mimotion#72]
![Uploading Screenshot_2021-04-21-18-26-32-495_com.qihoo.contents.jpg…]()
大兄弟帮忙看看

**Comment by Squaregentleman** [comment]
请重新上传图片

**Comment by zyx901212** [comment]
![Uploading Screenshot_2021-04-21-18-26-32-495_com.qihoo.contents.jpg…]()

**Comment by zyx901212** [comment]
我手机上传的不知道能看不

**Comment by Squaregentleman** [comment]
看不到图片

**Comment by zyx901212** [comment]
大佬，有其他联系方式吗？tg啥的

**Comment by zyx901212** [comment]
1
Run pip install requests
20
Collecting requests
21
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
22
Collecting urllib3<1.27,>=1.21.1
23
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
24
Collecting chardet<5,>=3.0.2
25
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
26
Collecting certifi>=2017.4.17
27
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
28
Collecting idna<3,>=2.5
29
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
30
Installing collected packages: urllib3, idna, chardet, certifi, requests
31
Successfully installed certifi-2020.12.5 chardet-4.0.0 idna-2.10 requests-2.25.1 urllib3-1.26.4
32
Traceback (most recent call last):
33
  File "main.py", line 221, in <module>
34
    push += main(user_list[line], passwd_list[line], step) + '\n'
35
  File "main.py", line 73, in main
36
    login_token,userid = login(user,password)
37
  File "main.py", line 31, in login
38
    location = r1.headers["Location"]
39
  File "/opt/hostedto

**Comment by zyx901212** [comment]
location = r1.headers["Location"]
39
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/requests/structures.py", line 54, in __getitem__
40
    return self._store[key.lower()][1]
41
KeyError: 'location'
42
Error: Process completed with exit code 1.

**Comment by Squaregentleman** [comment]
登录失败 请检查账号密码

**Comment by zyx901212** [comment]
账号我输入的手机号

**Comment by zyx901212** [comment]
大佬，注明一下，是小米运动的账号，而不是小米账号。


我一直以为的是小米账号

**Comment by Squaregentleman** [comment]
我改一下readme
